export const APPOINTMENT_ACTION_TYPES = {
  SELECT_APPOINTMENT: "SELECT_APPOINTMENT",
  UPDATE_APPOINTMENT: "UPDATE_APPOINTMENT",
  UPDATE_MODAL_FORM: "UPDATE_MODAL_FORM",
  TOGGLE_MODAL: "TOGGLE_MODAL",
  APPOINTMENT_LIST_REQUEST: "APPOINTMENT_LIST_REQUEST",
  APPOINTMENT_LIST_SUCCESS: "APPOINTMENT_LIST_SUCCESS",
  APPOINTMENT_LIST_FAIL: "APPOINTMENT_LIST_FAIL",
};
